### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by eggplantbren** [j-faria/kima#15]
I was running kima on a dataset of mine and it used up all my RAM and started using virtual memory. Obviously this is a problem that needs to be fixed.

**Comment by j-faria** [comment]
Is this related to #13?

**Comment by eggplantbren** [comment]
I don't know yet...

**Comment by eggplantbren** [comment]
Resolved (inelegantly) with b8341622bc9d05b2be2ea89a635438b50059efe6. This might help with #13.

**Comment by j-faria** [comment]
I was thinking this could be solved with a `setpars` method in each `ContinuousDistribution` such that
```c++
Pprior->setpars(center, width);
```
would work (assuming `Pprior` is Laplace)
