### ISSUE TITLE
Helpful header line (description functions)

### ISSUE THREAD

**Issue by eggplantbren** [j-faria/kima#17]
It would be helpful to have correct, non-summarised headers in sample.txt, so the user knows exactly what is in each column. This will involve writing the description functions well, and in such a way that handles all the different combinations of options the user might have.

**Comment by j-faria** [comment]
This should be easy to fix :crossed_fingers:

**Comment by eggplantbren** [comment]
Good, because I tried it but gave up because I was overwhelmed with trying to understand all the different option combinations!

**Comment by eggplantbren** [comment]
Nice!!!
