### ISSUE TITLE
DNest4 submodule does not compile with gcc 7.2.0

### ISSUE THREAD

**Issue by eggplantbren** [j-faria/kima#29]
I upgraded by Ubuntu installation and now have gcc 7.2.0. With this new version, I get an error message about bind not being a member of std. This has been fixed in upstream DNest4 (which we should be using anyway). Alternatively if you want to fix it in your copy of DNest4 you should just add #include <functional> to the top of Sampler.h.

**Comment by j-faria** [comment]
I guess we can close this one?

**Comment by j-faria** [comment]
Or, ideally, set up Travis to test different versions of gcc
