### ISSUE TITLE
OPTIONS files still seem weird

### ISSUE THREAD

**Issue by eggplantbren** [j-faria/kima#31]
I highly recommend the following default, or something very similar.

```
2
10000
10000
100
0
10
100
20000
```

Is there a reason for the choices in the repository?

**Comment by eggplantbren** [comment]
Fixed with 996f2e5e4aa20123ce0dc2ac0bd4f72f0ecd5b6a

**Comment by j-faria** [comment]
Thank you, I hadn't had time to look into this yet
