### ISSUE TITLE
make src/RVmodel

### ISSUE THREAD

**Issue by saeedm31** [j-faria/kima#66]
(base) shojjatpanah@mac-shojj-dock ~ % cd kima 
(base) shojjatpanah@mac-shojj-dock kima % make
Compiling: src/RVmodel.cpp
In file included from src/RVmodel.cpp:1:
src/RVmodel.h:137:81: error: non-constant-expression cannot be narrowed from type 'int' to
      'std::__1::vector<std::__1::shared_ptr<DNest4::ContinuousDistribution>,
      std::__1::allocator<std::__1::shared_ptr<DNest4::ContinuousDistribution> > >::size_type' (aka 'unsigned long') in initializer list
      [-Wc++11-narrowing]
        std::vector<std::shared_ptr<DNest4::ContinuousDistribution>> KO_Pprior {n_known_object};
                                                                                ^~~~~~~~~~~~~~
src/RVmodel.h:137:81: note: insert an explicit cast to silence this issue
        std::vector<std::shared_ptr<DNest4::ContinuousDistribution>> KO_Pprior {n_known_object};
                                                                                ^~~~~~~~~~~~~~
                                                                                static_cast<size_type>( )
src/RVmodel.h:138:81: error: non-constant-expression cannot be narrowed from type 'int' to
      'std::__1::vector<std::__1::shared_ptr<DNest4::ContinuousDistribution>,
      std::__1::allocator<std::__1::shared_ptr<DNest4::ContinuousDistribution> > >::size_type' (aka 'unsigned long') in initializer list
      [-Wc++11-narrowing]
        std::vector<std::shared_ptr<DNest4::ContinuousDistribution>> KO_Kprior {n_known_object};
                                                                                ^~~~~~~~~~~~~~
src/RVmodel.h:138:81: note: insert an explicit cast to silence this issue
        std::vector<std::shared_ptr<DNest4::ContinuousDistribution>> KO_Kprior {n_known_object};
                                                                                ^~~~~~~~~~~~~~
                                                                                static_cast<size_type>( )
src/RVmodel.h:139:81: error: non-constant-expression cannot be narrowed from type 'int' to
      'std::__1::vector<std::__1::shared_ptr<DNest4::ContinuousDistribution>,
      std::__1::allocator<std::__1::shared_ptr<DNest4::ContinuousDistribution> > >::size_type' (aka 'unsigned long') in initializer list
      [-Wc++11-narrowing]
        std::vector<std::shared_ptr<DNest4::ContinuousDistribution>> KO_eprior {n_known_object};
                                                                                ^~~~~~~~~~~~~~
src/RVmodel.h:139:81: note: insert an explicit cast to silence this issue
        std::vector<std::shared_ptr<DNest4::ContinuousDistribution>> KO_eprior {n_known_object};
                                                                                ^~~~~~~~~~~~~~
                                                                                static_cast<size_type>( )
src/RVmodel.h:140:83: error: non-constant-expression cannot be narrowed from type 'int' to
      'std::__1::vector<std::__1::shared_ptr<DNest4::ContinuousDistribution>,
      std::__1::allocator<std::__1::shared_ptr<DNest4::ContinuousDistribution> > >::size_type' (aka 'unsigned long') in initializer list
      [-Wc++11-narrowing]
        std::vector<std::shared_ptr<DNest4::ContinuousDistribution>> KO_phiprior {n_known_object};
                                                                                  ^~~~~~~~~~~~~~
src/RVmodel.h:140:83: note: insert an explicit cast to silence this issue
        std::vector<std::shared_ptr<DNest4::ContinuousDistribution>> KO_phiprior {n_known_object};
                                                                                  ^~~~~~~~~~~~~~
                                                                                  static_cast<size_type>( )
src/RVmodel.h:141:81: error: non-constant-expression cannot be narrowed from type 'int' to
      'std::__1::vector<std::__1::shared_ptr<DNest4::ContinuousDistribution>,
      std::__1::allocator<std::__1::shared_ptr<DNest4::ContinuousDistribution> > >::size_type' (aka 'unsigned long') in initializer list
      [-Wc++11-narrowing]
        std::vector<std::shared_ptr<DNest4::ContinuousDistribution>> KO_wprior {n_known_object};
                                                                                ^~~~~~~~~~~~~~
src/RVmodel.h:141:81: note: insert an explicit cast to silence this issue
        std::vector<std::shared_ptr<DNest4::ContinuousDistribution>> KO_wprior {n_known_object};
                                                                                ^~~~~~~~~~~~~~
                                                                                static_cast<size_type>( )
5 errors generated.
make: *** [src/RVmodel.o] Error 1
(base) shojjatpanah@mac-shojj-dock kima %

**Comment by j-faria** [comment]
What compiler are you using?

**Comment by saeedm31** [comment]
Hi there,
The problem was with the version of gcc compiler indeed (in mac os is gcc 4.2.1 or older)
I forced the "make" to use a specific version:
export CXX=g++-mp-5
export CC=gcc-5
or:
make CXX=g++-mp-5 CC=gcc-5

Cheers,
S
