### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by j-faria** [j-faria/kima#7]
We need to check for any license issue with celerite, eigen and DNest4

**Comment by jdavidrcamacho** [comment]
For what I can see DNest4 and celerite are under MIT licence and shouldn't give any trouble. Eigen is under BSD 3-Clause License that prohibits others from using the name of the project to promote derived products without written consent, not sure how that can be solved. :\

**Comment by j-faria** [comment]
I put `-DEIGEN_MPL2_ONLY` in the Makefile which should only use MPL2 licensed code from Eigen.  
I think it's ok, but let's check when we submit to JOSS

**Comment by j-faria** [comment]
Closing for now
