### ISSUE TITLE
Can you put the example data in the repository?

### ISSUE THREAD

**Issue by eggplantbren** [j-faria/kima#8]
I just cloned the repo and everything compiled with no problems. But when I try to run it, it says it can't find `data/data_to_test_priors.txt`. It'd be good to have that file in the repository.

**Comment by j-faria** [comment]
Fixed now, sorry about this.
I'm now using the simulated data in the BL2009 example. The options in OPTIONS are not ideal (in fact I'll open another issue to ask for your help on that)
