### ISSUE TITLE
nan information

### ISSUE THREAD

**Issue by j-faria** [j-faria/kima#9]
```
dnest4.py:175: RuntimeWarning: invalid value encountered in multiply
  H_estimates[z] = -logz_estimates[z] + np.sum(P_samples[:,z]*logl)
log(Z) = -106.72234101 +- 0.0
Information = nan +- nan nats.
```

This is happening in the BL2009 example

**Comment by j-faria** [comment]
This happens because some of the log-likelihoods are huge (negative) values and the multiplication underflows. 
I traced it back to the `log_likelihood` function, which outputs -1e300 when logL is infinite of nan

**Comment by j-faria** [comment]
Maybe @eggplantbren can help here, I'm not convinced that the sampling is going well on this example

**Comment by eggplantbren** [comment]
I'm getting a sensible value for the information. However, some other aspects of the run look unhealthy to me. I'll do some more investigation.

**Comment by j-faria** [comment]
This seems to be solved by the pull request so closing

**Comment by eggplantbren** [comment]
This is now occurring again on the many planets example. Reopening.

I tried running my own dnest4.classic.postprocess() instead of your edited one and it worked fine. That should be a big clue as to what the problem is. In the longer run it might be more elegant to have the submodule be standard DNest4 and move your new code (currently in your DNest4 fork) into kima.

**Comment by j-faria** [comment]
Yeah this is a problem with `pandas.read_csv` which reads values from sample_info.txt as `-inf`.
Since your `my_loadtxt` is actually faster, I agree we should just use that.

I like the idea of using standard DNest4. How do you propose we handle the other changes I did in my fork; the new distributions and the like? A pull request to DNest4?

**Comment by eggplantbren** [comment]
Make a pull request so I can see what would be in it. If it's not very disruptive (just new distributions, no API changes and such) I can just accept it.

**Comment by j-faria** [comment]
Feel free to re-open if the problem persists
